### ISSUE TITLE
How to parse json back to lua?

### ISSUE THREAD

**Issue by markonway** [fstirlitz/luaparse#112]
Hi everyone, I used luaparse to convert a LUA file to json and then modify it, but I wanted to convert it now (after modified) to LUA again, I couldn't find anything in the documentation on how to convert JSON to LUA, is there any method for this? what should I do?

**Comment by fstirlitz** [comment]
There is not a built-in serialiser. You need to walk the syntax tree yourself. See for example [luamin](https://github.com/mathiasbynens/luamin).
