### ISSUE TITLE
Lua floor division operator not recognised

### ISSUE THREAD

**Issue by AlexanderMisel** [fstirlitz/luaparse#114]
See for example this code:
```lua
function round(v, step)
    return math.tointeger((v + step*0.5) // step * step)
end
```

Related Ace Editor issue: https://github.com/ajaxorg/ace/issues/4571

```
[2:42] <expression> expected near '/'
```

**Comment by fstirlitz** [comment]
This is already supported and tested:

https://github.com/fstirlitz/luaparse/blob/d61c6fe1cd2757bc210898bc9b263ffe4adbd060/luaparse.js#L775-L779

https://github.com/fstirlitz/luaparse/blob/d61c6fe1cd2757bc210898bc9b263ffe4adbd060/test/scaffolding/operators#L35-L40

Ace will have to enable the `"luaVersion": "5.3"` option.
