### ISSUE TITLE
Incorrect parsing for return statements

### ISSUE THREAD

**Issue by omarkmu** [fstirlitz/luaparse#122]
When immediately followed by comma without an initial expression, the `return` statement should result in a syntax error. Currently, as long as a "second" expression is included, the parser does not recognize this. So, `return, 1` is considered valid. [This](https://github.com/fstirlitz/luaparse/blob/0b6511054db161623c838e54d3b481648419d014/luaparse.js#L1922) code seems to be the culprit. Note that if the expression after the comma is excluded, this correctly emits a syntax error.

**Comment by fstirlitz** [comment]
Fixed by 0f525b152516bc8afa34564de2423b039aa83bc1, thank you.
