### ISSUE TITLE
variable with negative Integer/Number gives UnaryExpression

### ISSUE THREAD

**Issue by Bizarrus** [fstirlitz/luaparse#51]
Sample Line:
```lua
priority = -1
```
Currently fixing with follwing:
```javascript
switch(content.type) {
    // Default numbers
    case 'NumericLiteral':
        value = parseInt(content.value, 10);
    break;

    case 'UnaryExpression':
        /* Fix parsing error for negative numbers */
        if(content.operator == '-') {
            value = -parseInt(content.argument.value, 10);
        }
    break;
}
```

**Comment by fstirlitz** [comment]
Latest git master returns this for your example:
```json
    {
      "type": "AssignmentStatement",
      "variables": [
        {
          "type": "Identifier",
          "name": "priority"
        }
      ],
      "init": [
        {
          "type": "UnaryExpression",
          "operator": "-",
          "argument": {
            "type": "NumericLiteral",
            "value": 1,
            "raw": "1"
          }
        }
      ]
    }
```

It seems like a valid interpretation to me, even if a bit silly. I'm not sure if Lua considers `-1` a single token or not, but either way it is read, the expression evaluates to the same value.

Your 'fix' doesn't check that the underlying operand is a `NumericLiteral`; it'll crash on `-x`. And why call `parseInt` on a value that is already an integer?

**Comment by oxyc** [comment]
Lua does the same:
- https://github.com/lua/lua/blob/master/llex.c#L443
- https://github.com/lua/lua/blob/master/llex.c#L214
- https://github.com/lua/lua/blob/master/lparser.c#L989

If I recall the bison/flex grammars I looked at as well as esprima/acorn does this too.
