### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by Teoxoy** [fstirlitz/luaparse#63]
Consider publishing a new version to npm.

[0.2.1](https://www.npmjs.com/package/luaparse/v/0.2.1) was published 3 years ago.
From an outside perspective the project looks dead even though there have been [quite a few changes](https://github.com/oxyc/luaparse/compare/v0.2.1...master).

**Comment by fstirlitz** [comment]
Well, it actually is barely, and mostly passively maintained. @oxyc has not been active here lately, and I don't have access to his npm credentials. Don't expect a new release soon.

**Comment by oxyc** [comment]
I apologize for my absence and unfortunately I don't see it changing either. Life...

@fstirlitz do you have a npm username and I can give you access? And to be honest, as I'm really not a maintainer anymore feel free to move the project in any direction you see fit. If you're interested I can transfer the ownership of this project to you as well.

**Comment by Teoxoy** [comment]
@oxyc Things happen... Glad to hear you don't want to let the project die tho ;) I appreciate your work

**Comment by fstirlitz** [comment]
I did not until now; it's `felix.s`. I've already got a couple of ideas where to take this project forward, so I'll be fine with taking it over.

I'm still not promising a release soon, though.

**Comment by Teoxoy** [comment]
@fstirlitz My intention wasn't really to get a new release. I wanted to spark a conversation regarding the maintenance of the project. Releases will come naturally as long as it's maintained.

**Comment by fstirlitz** [comment]
Apparently @oxyc gave me access a while ago. I didn't notice until now; no notification was sent.

Anyway: the next version will be 0.3 and it shall (I hope) feature fixes for [the issues listed for the milestone](https://github.com/oxyc/luaparse/milestone/1). Planned release date: When It's Done©®™.

(When It's Done©®™ is a trademark of Apogee Software Ltd.©®™ aka 3D Realms©®™.)

**Comment by fstirlitz** [comment]
Fixed in 49776a01d537ce1517c5af0e41417c45c7635c89.
