### ISSUE TITLE
Rename arguments in TableCallExpression node to argument

### ISSUE THREAD

**Issue by omegalink12** [fstirlitz/luaparse#69]
TableCallExpression currently puts the function argument in the property arguments which leads to a minor inconsistency as it is expected to be an array. This should be renamed to argument as there will always only be one. This also makes it consistent with StringCallExpression

**Comment by fstirlitz** [comment]
Ordinarily I would say this isn't worth breaking backwards compatibility (cf. `Referer`), but given that I'm planning some backwards-incompatible changes soon anyway, maybe I'll be able to get away with this too.
