### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by berbun** [fstirlitz/luaparse#75]
There are a couple of mispelling/typos in the comments.
These can be easily noticed and fixed.
I think I will make a PR for this.

**Comment by fstirlitz** [comment]
I mean, please do. Why even open a separate issue? If you know how to fix it, just submit a PR straight away.

**Comment by berbun** [comment]
> I mean, please do. Why even open a separate issue? If you know how to fix it, just submit a PR straight away.

Perhaps, because I want to teach you something new along this way.. 😄

**Comment by fstirlitz** [comment]
No PR in sight and no specific typos pointed out. Closing.

**Comment by berbun** [comment]
> No PR in sight and no specific typos pointed out. Closing.

I had commited changes in offline, I had fixed a couple of typos but I'm offgrid. No power since 3 days.
Unfortunately, I don't know when we are getting the power back on.

(This message was sent from my friend's phone <3)
