### ISSUE TITLE
Modernize the project (ES6) 🚀

### ISSUE THREAD

**Issue by berbun** [fstirlitz/luaparse#76]
Some of the common findings, which could be applied to the current codebase include:
- Use classes. (`FullFlowContext`, `LoopFlowContext`, lexer, parser, locationtracker)
- Stop using `var`; use `let` / `const` instead. (can be fixed automatically)
- Use (fat) arrow (function syntax). (can be fixed automatically)

Pro tip: Targetting newer ECMAScript standard means lesser support. **But**, honestly who on earth needs IE6 support in 2019; Windows XP has been officially dropped out a while ago...

Bonus tip: Achieve modularity. And general separation of different purposes/functionalities per file (ES2015 moduling) instead of a **monolithic** single JS code file, this would help everyone in every aspect. (For example: Smoother coding experience. Would also help at avoiding PR merge-conflicts. It will also help focus on one particular thing at the time.. Generally, easier to maintain code.)

Bonus pro tips:
- [ ] Add [Code of Conduct](https://help.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project).
- [ ] Define code-style/conventions guide (for contributors, usually called `CONTRIBUTING.md`).
- [ ] Create [issue/PR templates for GitHub](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates).
- [ ] Enhance discoverability of the repository by [adding topics on the repository](https://user-images.githubusercontent.com/34973365/67618520-e05e5100-f7f0-11e9-9f7c-2dd5bf3d4f78.png). (For example: `lua`, `luajit`, `parser`, `javascript-library`, `luaparse`..)
- [ ] Create `luaparse` logo. 🎨
- [ ] Create actual documentation using [`Wiki`](https://github.com/oxyc/luaparse/wiki) (or use [Readthedocs](https://readthedocs.org/) and disable the `Wiki` page).
- [ ] Actually, use [`Projects`](https://github.com/oxyc/luaparse/projects) Board page to help organize what is currently being worked on. That way everyone will know what's the current status/progress..
- [ ] Improve/Update Readme to reflect all the breaking changes. And perhaps also state that `v0.x` is unstable? (to let people know `luaparse` can and will make breaking changes until `v1.0`)
- [ ] Do we have Discord server? If no, make one! 😄 
- [ ] Automate deployment of npm package (utilize 'nightly' versioning). Relates to #63.
- [ ] Create/Host `luaparse` app at [Heroku](https://heroku.com) (it is completely free!); make some sort of "Playground" (aka "Try it online"), so people could see AST in real-time while typing out Lua code in Ace editor. I think maybe even GitHub Pages would work for hosting it.

Did I forget something? 🤔

**Comment by berbun** [comment]
@oxyc @fstirlitz 
But above all.
Outdated and deprecated `npm` dependencies, unfortunately it is worst than you think:
```
npm WARN deprecated gulp-header@1.8.12: Removed event-stream from gulp-header
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated istanbul@0.3.22: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 633 packages from 696 contributors and audited 7632 packages in 24.774s
found 22 vulnerabilities (10 low, 2 moderate, 10 high)
```

**10 high**. This scares me a little, it really does. Reasonably, since I am a complete noob at NodeJS (I literally started doing JS and stuff, since last week).
Take a close look at the very bottom line. My advice: I highly suggest to modernize, start by upgrading and using newer versions of dependencies (or their successors).

**Comment by fstirlitz** [comment]
Yes, you did: a justification for all of this.

I am not interested in chasing fashions and breaking compatibility for its own sake. Maintaining ES3 compatibility has worked rather well for this project so far, and I see no compelling reason to abandon it. Most ES6-related changes proposed here are trivial syntax changes that bring no tangible benefit whatsoever.

The dependencies are only used for development; linters, test runner and so on. luaparse has no production-time dependencies, which means those who don't develop luaparse are not affected by the vulnerabilities, whatever they are, and those who do on trusted inputs. Outdated build dependencies are kind of bad, but not tragic to the point of uselessness. Updating those is covered by #66 anyway.
