### ISSUE TITLE
Parse error syntax does not raise an error

### ISSUE THREAD

**Issue by liwangqian** [fstirlitz/luaparse#80]
When parse the expression like:
```lua
local xxx = true
if ~xxx then
   print("xxxx")
end
```
The parser does not report an syntax error.

**Comment by fstirlitz** [comment]
Can you reproduce with latest git master?

**Comment by fstirlitz** [comment]
The report provides very little context, but I believe the actual problem was fixed in af602e14ef887f735f64663fd722c6a44729c72c. Closing.
