### ISSUE TITLE
`...` can be used outside a vararg function if it's used in the root scope

### ISSUE THREAD

**Issue by Qix-** [fstirlitz/luaparse#84]
`...` is passed the arguments to `lua_pcall()` (or to `load(s)(...)`). However, luaparse incorrectly throws a syntax error.

It looks like this edge case was missed in #74.

**Comment by Qix-** [comment]
Nevermind, there was a problem on our end. The fact the error messages are the same confused me.

**Comment by fstirlitz** [comment]
I mean, I [even added a test for this case](https://github.com/fstirlitz/luaparse/commit/f3354f3a25211429663c4c69337dc30cb76942f8#diff-ce5e122c2bc6d33a6136a3d11530418cR44), so it would be strange if it failed to work.
