### ISSUE TITLE
Bitwize brackets disappears

### ISSUE THREAD

**Issue by Heronbeluci** [fstirlitz/luaparse#93]
Well, after some troubles with bitwise, i come to this, a dead end...

Code: `local hello = (1 << 1)`
Result: `local b=1<<1`

The problem? my brackets!
I want them!

i need them to work with a bitwise operation...

Work (Before parse): `local b = ((0 << 0) & 0xFF) + ((53 << 8) & 0xFFFF) + ((12 << 16) & 0xFFFFFF) + ((0 << 24) & 0xFFFFFFFF);print('Result: '..b)`

Dont Work (After parse): `local b=0<<0&0xFF+53<<8&0xFFFF+12<<16&0xFFFFFF+0<<24&0xFFFFFFFF;print(b)`

![image](https://user-images.githubusercontent.com/15113966/104774186-fee19c80-5754-11eb-8183-4ae70a10bbea.png)

**Comment by fstirlitz** [comment]
You posted this in the wrong project. This is not a minifier.
